---
title: "Student Wrangling"
output: pdf_document
date: '2023-03-06'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rsample)
library(caret)
library(keras)
library(tidymodels)
library("midfieldr")
library("midfielddata")
suppressMessages(library("data.table"))
library(metan)
library(readxl)
data(student)
```
```{r}
#select variables we are interested in 
student_1 <- student %>% 
  select(hours_transfer, age, act_comp, sat_verbal, sat_math) %>% 
  #rescale to be on 0,1 scale
  resca(new_min = 0, new_max = 1, keep = FALSE) %>%
  #replace NA's with -1
  replace(is.na(.), -1)

student_stand <- cbind(student[,c( "mcid","transfer", "race", "sex", "us_citizen")], student_1) %>%
  filter(sex != "Unknown") %>% #Exactly one student is unknown, filter out
  #covert categorical to numeric
  mutate(sex = if_else(sex == "Male", 1,0), 
         transfer = if_else(transfer == "First-Time Transfer",1,0),
         us_citizen = 
           case_when(
            us_citizen == "Yes" ~ 1,
            us_citizen == "No" ~ 0,
            is.na(us_citizen) ~ -1
           ),
         race = 
           case_when(
             race == "Asian" ~ 1,
             race == "Black" ~ 2,
             race == "Hispanic/Latinx" ~ 3,
             race == "International" ~ 4,
             race == "Native American" ~ 5,
             race == "Other/Unknown" ~ 6, 
             race == "White" ~ 7
           ) 
         )

```


```{r}
save(student_stand, file ="student_stand.Rda")
```



