---
title: "Student and terms wrangling"
output: pdf_document
date: '2023-03-06'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rsample)
library(caret)
library(keras)
library(tidymodels)
library("midfieldr")
library("midfielddata")
suppressMessages(library("data.table"))
library(metan)
library(readxl)
data(student, degree, term)
```
```{r}
#select variables we are interested in 
student_1 <- student %>% 
  select(hours_transfer, age, act_comp, sat_verbal, sat_math) %>% 
  #rescale to be on 0,1 scale
  resca(new_min = 0, new_max = 1, keep = FALSE) %>%
  #replace NA's with -1
  replace(is.na(.), -1)

student_stand <- cbind(student[,c( "mcid","transfer", "race", "sex", "us_citizen")], student_1) %>%
  filter(sex != "Unknown") %>% #Exactly one student is unknown, filter out
  #covert categorical to numeric
  mutate(sex = if_else(sex == "Male", 1,0), 
         transfer = if_else(transfer == "First-Time Transfer",1,0),
         us_citizen = 
           case_when(
            us_citizen == "Yes" ~ 1,
            us_citizen == "No" ~ 0,
            is.na(us_citizen) ~ -1
           ),
         race = 
           case_when(
             race == "Asian" ~ 1,
             race == "Black" ~ 2,
             race == "Hispanic/Latinx" ~ 3,
             race == "International" ~ 4,
             race == "Native American" ~ 5,
             race == "Other/Unknown" ~ 6, 
             race == "White" ~ 7
           ) 
         )
```

```{r}
#determining stem grads
data(student, degree)
 
#Get eligible stem cip codes from DHS 
STEM_CIP <- read_excel("~/OneDrive/Documents/Deep Learning Codes/STEM_CIP_new.xlsx")
#extra stem codes to include broader categories 
stem_list = c(40,27,26,14)  #schools can have majors that aren't anywhere else 


#If there is no degree for student, not a grad so not a stem grad
#ifelse they are grad so check if stem grad.
#Need to check the full cip6 and the first two digits
std_degree <- left_join(student, degree %>% select(mcid, degree_cip6 = cip6) %>% mutate(is_grad = 1)) %>% 
  mutate(is_stemGrad = ifelse((is_grad == "1" & degree_cip6 %in% STEM_CIP | (substring(degree_cip6,1,2) %in% stem_list)),1,0 )) %>%
  replace(is.na(.), 0) %>% #If NA, replace with zero 
  select(mcid,  is_stemGrad)  #is_stemGrad binary target 
```

```{r}

term_no_na <- term %>%filter(!is.na(institution), #Keras can't handle any NA's so filter
              !is.na(cip6),
              !is.na(level),
              !is.na(standing),
              !is.na(hours_term_attempt),
              !is.na(hours_term),
              !is.na(hours_cumul),
              !is.na(hours_cumul_attempt),
              !is.na(gpa_term),
              !is.na(gpa_cumul))
terms_t1<- left_join( term_no_na %>%   
              group_by(mcid) %>% #group by each student
              
              #How many terms the student is in good standing
              mutate(NumGoodTerms = sum(standing == "Good Standing"),
              #How many terms the student is on academic probation  
              NumProbationTerms = sum(standing == "Academic Probation")) %>% 
              #Level is grade 1 being freshmen, 4 being senior
              mutate(level = case_when(
                level %like% "^01" ~ 1,
                level %like% "^02" ~ 2,
                level %like% "^03" ~ 3,
                level %like% "^04" ~4
            )) %>%
        #We want to know what grade they were in in their last term
            filter(level == max(level)) %>%
            rename(highest_level = level) %>%
            select(mcid,highest_level, NumGoodTerms, NumProbationTerms) %>%
            distinct() , #break it down to one entry per student
          
          term_no_na %>%
          group_by(mcid) %>%
          #what was each students average hours per term
          summarize(avg_hours_per_term = mean(hours_term, na.rm = TRUE))) %>% 
  
        left_join(
          term_no_na %>%
            group_by(mcid) %>%
            arrange(desc(term)) %>%
            slice(1) %>%
            #GPA in last term (useful since most don't graduate)
            select(mcid, final_gpa = gpa_cumul)
        )

#Identifying student's change of majors
  cip6_tbl <- left_join(
    #Student's first declared major
  term_no_na %>%
    group_by(mcid) %>%
    filter(term == min(term)) %>%
    distinct(mcid, cip6, .keep_all = FALSE) %>%
    select(mcid, initial_cip6 = cip6),
  #Student's last declared major
  #don't actually use in the model, just for testing purposes
  term_no_na %>%
    group_by(mcid) %>%
    filter(term == max(term)) %>%
    distinct(mcid, cip6, .keep_all = FALSE) %>%
    select(mcid, final_cip6 = cip6)
) %>% left_join(
  ##The major the student declared for the most terms
  term_no_na %>%
    distinct(mcid, term, cip6) %>%
    group_by(mcid, cip6) %>%
    summarize(n = n()) %>%
    arrange(desc(n)) %>%
    slice(1) %>%
    select(mcid, most_prevalent_cip6 = cip6),
  by = "mcid"
) %>% left_join(
  #how many times they changed their major 
  term_no_na %>%
    distinct(mcid, cip6, .keep_all = FALSE) %>%
    group_by(mcid) %>%
    summarize(major_changes = n() - 1)
  #Conver to numeric 
) %>% mutate(initial_cip6 = as.numeric(initial_cip6),
    final_cip6 = as.numeric(final_cip6),
    most_prevalent_cip6 = as.numeric(most_prevalent_cip6))  
  
#Cip6 of 999999 is undeclared, filter out because they give us zero information 
term_tbl <- cip6_tbl %>%
  distinct() %>%
  group_by(mcid) %>%
  mutate(n = n()) %>%
  filter(ifelse(n == 1, TRUE, initial_cip6 != 999999 & final_cip6 != 999999 & most_prevalent_cip6 != 999999)) %>%
  select(-n) %>%
  slice(1) %>%
  left_join(terms_t1)

#rescale numeric data to be between 0 and 1
terms_stnd <- cbind(term_tbl[,1:4], term_tbl[,5:10] %>% resca(new_min = 0, new_max = 1, keep = FALSE))           

```
```{r}
#create boolean that gives whether a students first declared major was STEM 
inititalCIP_stem <- term_tbl %>% 
                    mutate(initialCIP_stem = ifelse(((initial_cip6 %in% STEM_CIP) |(substring(initial_cip6,1,2) %in% stem_list)) ,1,0)) %>% 
                    select(mcid, initialCIP_stem)
```

```{r}
#We will use student as truth, aka only include student's that were in the student table. Keras cannot handle any Na's  
mcid_keep <- student_stand %>%
  distinct(mcid) %>%
  pull(mcid)

student_terms <-  student_stand %>%   
  filter(mcid != 'MID26178202') %>%  #the one student with sex undeclared needs to be filtered out of all tables
  left_join(
    inititalCIP_stem %>%   
      filter(mcid %in% mcid_keep)) %>% 
  left_join(std_degree %>%  #97460
      filter(mcid %in% mcid_keep)) %>%
  left_join(
    terms_stnd %>%   #95943
      filter(mcid %in% mcid_keep)
  ) 

student_terms <- student_terms[complete.cases(student_terms)]
```
```{r}
save(student_terms, file = "student_terms_new.Rda")
```

